version: '3.1'
services:

  webapp:
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080